

```{r bikeshare Data}

getwd()
list.files()

wash <- read.csv('washington.csv')
names(wash)
ny <- read.csv('new_york_city.csv')
names(ny)
head(ny)
class(chi$Start.Time)
chi <- read.csv('chicago.csv')
names(chi)

```



install.packages('ggplot2')
library(ggplot2)

install.packages('ggthemes', dependencies = TRUE)
library(ggthemes)




# Install lubridate package
install.packages("lubridate")
library(lubridate)

# ----------------------------------------------
# most common month, day, hour per city? 
# ----------------------------------------------

# hour -------------------

ny$start <- as.POSIXlt(ny$Start.Time, format="%Y-%m-%d%H:%M")
h_count_ny <- table(format(as.POSIXct(ny$start), format="%H"))
max_h_ny <- subset(h_count_ny, h_count_ny==max(h_count_ny))
max_h_ny

chi$start <- as.POSIXlt(chi$Start.Time, format="%Y-%m-%d%H:%M")
h_count_chi <- table(format(as.POSIXct(chi$start), format="%H"))
max_h_chi <- subset(h_count_chi, h_count_chi==max(h_count_chi))
max_h_chi

wash$start <- as.POSIXlt(wash$Start.Time, format="%Y-%m-%d%H:%M")
h_count_wash <- table(format(as.POSIXct(wash$start), format="%H"))
h_count_wash
max_h_wash <- subset(h_count_wash, h_count_wash==max(h_count_wash))
max_h_wash

# plot -------

max_hour <- rbind(table(format(as.POSIXct(ny$start), format="%H")), table(format(as.POSIXct(chi$start), format="%H")), table(format(as.POSIXct(wash$start), format="%H")))
barplot(max_hour, main="hours", ylab="count", col=terrain.colors(3), beside=T)
legend(2, 35000, legend=c("ny", "chi", "wash"), fill=terrain.colors(3))

  

# month -------------------

chi$Start.Time <- as.Date(chi$Start.Time)
month_count_chi <- table(months(chi$Start.Time))
max_month_chi <- subset(month_count_chi, month_count_chi==max(month_count_chi))
max_month_chi
wash$Start.Time <- as.Date(wash$Start.Time)
month_count_wash <- table(months(wash$Start.Time))
max_month_wash <- subset(month_count_wash, month_count_wash==max(month_count_wash))
max_month_wash
ny$Start.Time <- as.Date(ny$Start.Time)
month_count_ny <- table(months(ny$Start.Time))
max_month_ny <- subset(month_count_ny, month_count_ny==max(month_count_ny))
max_month_ny

# plot -------

max_month <- rbind(month_count_ny,month_count_chi, month_count_wash)
max_month
barplot(max_month, main="max_month", ylab="count", col=terrain.colors(3), beside=T)
legend(2, 90000, legend=c("ny", "chi", "wash"), fill=terrain.colors(3))



# day -------------------

ny$Start.Time <- as.Date(ny$Start.Time)
day_count_ny <- table(weekdays(ny$Start.Time))
max_day_ny <- subset(day_count_ny, day_count_ny==max(day_count_ny))
max_day_ny
wash$Start.Time <- as.Date(wash$Start.Time)
day_count_wash <- table(weekdays(wash$Start.Time))
max_day_wash <- subset(day_count_wash, day_count_wash==max(day_count_wash))
max_day_wash
chi$Start.Time <- as.Date(chi$Start.Time)
day_count_chi <- table(weekdays(chi$Start.Time))
max_day_chi <- subset(day_count_chi, day_count_chi==max(day_count_chi))
max_day_chi

# plot -------

max_day <- rbind(day_count_ny,day_count_chi, day_count_wash)
max_day
class(max_day)

barplot(max_day,
        main="max_day",
        ylab="count",
        col=terrain.colors(3),
        beside=T)
legend(2, 15000, legend=c("ny", "chi", "wash"), fill=terrain.colors(3))


# ----------------------------------------------
# most common start, end station & trip per city? 
# ----------------------------------------------

# start station
subset(table(ny$Start.Station), table(ny$Start.Station)==max(table(ny$Start.Station)))
subset(table(wash$Start.Station), table(wash$Start.Station)==max(table(wash$Start.Station)))
subset(table(chi$Start.Station), table(chi$Start.Station)==max(table(chi$Start.Station)))

# end station
subset(table(ny$End.Station), table(ny$End.Station)==max(table(ny$End.Station)))
subset(table(wash$End.Station), table(wash$End.Station)==max(table(wash$End.Station)))
subset(table(chi$End.Station), table(chi$End.Station)==max(table(chi$End.Station)))

# trip
ny$trip <- paste(ny$Start.Station, ny$End.Station)
subset(table(ny$trip), table(ny$trip)==max(table(ny$trip)))
chi$trip <- paste(chi$Start.Station, chi$End.Station)
subset(table(chi$trip), table(chi$trip)==max(table(chi$trip)))
wash$trip <- paste(wash$Start.Station, wash$End.Station)
subset(table(wash$trip), table(wash$trip)==max(table(wash$trip)))


# ----------------------------------------------
# total/average trip duration per city? 
# ----------------------------------------------

total.trip <- sum(ny$Trip.Duration)
total.trip
avg.trip <- mean(ny$Trip.Duration)
avg.trip
total_y <- total.trip%/%(365*24*60*60)
total_y
rest_y <- total.trip%%(365*24*60*60)
rest_y
total_d <- rest_y%/%(60*60*24)
total_d
rest_d <- rest_y%%(60*60*24)
rest_d
total_h <- rest_d%/%(60*60)
total_h
rest_h <- rest_d%%(60*60)
rest_h
total_min <- rest_h%/%(60)
total_min
rest_sec <- rest_h%%(60)
rest_sec

#print("total trip: ", total_y,"years",total_d, "days", total_h, "hours", rest_sec, "sec")

total_y
total_d
total_h
total_min
rest_sec


# ----------------------------------------------
# user type, gender, dob-stats per city? 
# ----------------------------------------------

# counts of user type
ny_type <- data.frame(table(ny$User.Type))
chi_type <- data.frame(table(chi$User.Type))
wash_type <- data.frame(table(wash$User.Type))

# plot ---------

ny_chi_merge <- merge.data.frame(ny_type, chi_type, by = "Var1" , all=T)
all_merge <- merge.data.frame(ny_chi_merge, wash_type, by = "Var1", all=T)
colnames(all_merge) <- c("user_type","ny","chi","wash")
all_merge
rownames(all_merge) <- all_merge$user_type
rownames(all_merge)[1] <- 'not_specified'
all_merge[1] <- NULL
all_merge

barplot(t(as.matrix(all_merge)),
        main="user types per city",
        ylab="count",
        col=terrain.colors(3),
        beside=TRUE)
legend(2, 100000, legend=c("ny", "chi", "wash"), fill=terrain.colors(3))


# counts of gender
table(ny$Gender)
table(chi$Gender)

gender_ny_chi <- rbind(table(ny$Gender), table(chi$Gender))
colnames(gender_ny_chi)[1] <- 'not_specified'
gender_ny_chi
barplot(gender_ny_chi,
        col=terrain.colors(2),
        beside=T,
        ylab='count',
        main='gender count per city')
legend(2, 150000, legend=c("ny", "chi"), fill=terrain.colors(2))



# most common bday
bd_count_ny <- table(ny$Birth.Year)
most_common_bd_ny <- subset(bd_count_ny, bd_count_ny==max(bd_count_ny))
most_common_bd_ny
bd_count_chi <- table(chi$Birth.Year)
most_common_bd_chi <- subset(bd_count_chi, bd_count_chi==max(bd_count_chi))
most_common_bd_chi

# most recent bday
max(na.omit(ny$Birth.Year))
max(na.omit(chi$Birth.Year))


# most earliest bday
min(na.omit(ny$Birth.Year))
min(na.omit(chi$Birth.Year))

